In [2]:
import pandas as pd
import numpy as np
import seaborn as sns

df = pd.read_csv("NEW.csv")

In [6]:
df.head()

   Temperature  Salinity    DO%    PH  Turbidity  Label
0        13.16     33.06  82.90  7.88        3.3      0
1        13.18     33.13  83.50  7.89        4.4      0
2        13.13     33.25  84.20  7.90        4.6      0
3        13.10     33.34  84.81  7.91        5.8      0
4        13.05     33.45  85.60  7.92        3.5      0

In [7]:
import random
df.dropna(inplace = True)
df

       Temperature  Salinity    DO%    PH  Turbidity  Label
0            13.16     33.06  82.90  7.88        3.3      0
1            13.18     33.13  83.50  7.89        4.4      0
2            13.13     33.25  84.20  7.90        4.6      0
3            13.10     33.34  84.81  7.91        5.8      0
4            13.05     33.45  85.60  7.92        3.5      0
5            12.92     33.67  88.50  7.95        7.6      0
6            12.86     33.74  88.00  7.96        8.8      0
7            12.80     33.80  88.81  7.97        7.5      0
8            12.79     33.84  91.20  7.98        6.5      0
9            12.86     33.72  93.00  7.97        8.7      0
10           12.60     32.79  84.60  7.90        4.3      0
11           12.58     32.87  84.90  7.91        4.4      0
12           12.56     33.00  85.10  7.92        4.5      0
13           12.50     33.29  85.20  7.94        5.8      0
14           12.49     33.54  86.70  7.96        4.6      0
15           12.51     34.03  91.50  8.01        2.4      0
16           12.13     33.58  94.81  8.03        6.9      0
17           12.03     33.89  98.81  8.09       16.2      0
18           11.98     33.54  95.10  8.04        9.9      0
19           11.88     33.24  90.70  7.99        8.5      0
20           11.69     32.65  87.70  7.97        0.2      0
21           12.18     32.68  88.90  7.92        5.9      0
22           12.16     32.74  89.50  7.94        6.1      0
23           12.11     32.92  90.20  7.96        5.1      0
24           12.07     33.16  90.10  7.98        4.5      0
25           11.88     33.43  91.00  8.02        5.3      0
26           11.73     33.04  90.20  8.00        3.9      0
27           11.62     32.49  87.81  7.96        0.9      0
28           12.18     32.06  84.20  7.84        0.2      0
29           12.16     32.11  84.60  7.85        1.3      0
...            ...       ...    ...   ...        ...    ...
39968        15.10     26.88  89.60  8.02       50.8      0
39969        15.10     26.85  88.70  8.00       69.7      0
39970        15.12     26.92  89.10  8.01       77.2      0
39971        15.19     26.95  91.20  8.02       83.6      0
39972        15.23     26.96  92.40  8.03       77.7      0
39973        15.31     26.94  92.70  8.03       73.3      0
39974        15.37     26.92  92.90  8.03       95.4      0
39975        15.41     26.89  92.80  8.02       85.5      0
39976        15.48     26.86  92.80  8.02       86.5      0
39977        15.52     26.85  92.10  8.02       93.5      0
39978        15.66     26.73  92.20  8.01       98.3      0
39979        15.72     26.67  91.80  8.00      106.9      0
39980        15.78     26.64  91.50  8.00       88.1      0
39981        15.82     26.60  90.90  7.99       98.3      0
39982        15.88     26.54  90.40  7.98      149.2      0
39983        15.99     26.45  89.30  7.96      127.1      0
39984        16.04     26.34  88.50  7.95      126.6      0
39985        16.07     26.21  87.50  7.94      147.3      0
39986        16.09     26.16  87.30  7.94      115.6      0
39987        16.12     26.12  87.40  7.94      105.5      0
39988        16.18     26.09  89.30  7.98       77.6      0
39989        16.23     26.19  90.80  8.02       64.2      0
39990        16.37     26.21  92.30  8.10       14.3      0
39991        16.34     26.07  92.30  8.06       10.5      0
39992        16.33     25.96  92.10  8.03        9.7      0
39993        16.30     25.79  92.20  7.98       15.3      0
39994        16.28     25.75  92.20  7.97       15.6      0
39995        16.30     25.77  92.20  7.99       17.6      0
39996        16.34     25.84  92.40  8.01       19.2      0
39997        16.39     25.97  92.90  8.05       17.3      0

[39988 rows x 6 columns]

In [8]:
df_work = df
df_work['Label']=0
df_work

       Temperature  Salinity    DO%    PH  Turbidity  Label
0            13.16     33.06  82.90  7.88        3.3      0
1            13.18     33.13  83.50  7.89        4.4      0
2            13.13     33.25  84.20  7.90        4.6      0
3            13.10     33.34  84.81  7.91        5.8      0
4            13.05     33.45  85.60  7.92        3.5      0
5            12.92     33.67  88.50  7.95        7.6      0
6            12.86     33.74  88.00  7.96        8.8      0
7            12.80     33.80  88.81  7.97        7.5      0
8            12.79     33.84  91.20  7.98        6.5      0
9            12.86     33.72  93.00  7.97        8.7      0
10           12.60     32.79  84.60  7.90        4.3      0
11           12.58     32.87  84.90  7.91        4.4      0
12           12.56     33.00  85.10  7.92        4.5      0
13           12.50     33.29  85.20  7.94        5.8      0
14           12.49     33.54  86.70  7.96        4.6      0
15           12.51     34.03  91.50  8.01        2.4      0
16           12.13     33.58  94.81  8.03        6.9      0
17           12.03     33.89  98.81  8.09       16.2      0
18           11.98     33.54  95.10  8.04        9.9      0
19           11.88     33.24  90.70  7.99        8.5      0
20           11.69     32.65  87.70  7.97        0.2      0
21           12.18     32.68  88.90  7.92        5.9      0
22           12.16     32.74  89.50  7.94        6.1      0
23           12.11     32.92  90.20  7.96        5.1      0
24           12.07     33.16  90.10  7.98        4.5      0
25           11.88     33.43  91.00  8.02        5.3      0
26           11.73     33.04  90.20  8.00        3.9      0
27           11.62     32.49  87.81  7.96        0.9      0
28           12.18     32.06  84.20  7.84        0.2      0
29           12.16     32.11  84.60  7.85        1.3      0
...            ...       ...    ...   ...        ...    ...
39968        15.10     26.88  89.60  8.02       50.8      0
39969        15.10     26.85  88.70  8.00       69.7      0
39970        15.12     26.92  89.10  8.01       77.2      0
39971        15.19     26.95  91.20  8.02       83.6      0
39972        15.23     26.96  92.40  8.03       77.7      0
39973        15.31     26.94  92.70  8.03       73.3      0
39974        15.37     26.92  92.90  8.03       95.4      0
39975        15.41     26.89  92.80  8.02       85.5      0
39976        15.48     26.86  92.80  8.02       86.5      0
39977        15.52     26.85  92.10  8.02       93.5      0
39978        15.66     26.73  92.20  8.01       98.3      0
39979        15.72     26.67  91.80  8.00      106.9      0
39980        15.78     26.64  91.50  8.00       88.1      0
39981        15.82     26.60  90.90  7.99       98.3      0
39982        15.88     26.54  90.40  7.98      149.2      0
39983        15.99     26.45  89.30  7.96      127.1      0
39984        16.04     26.34  88.50  7.95      126.6      0
39985        16.07     26.21  87.50  7.94      147.3      0
39986        16.09     26.16  87.30  7.94      115.6      0
39987        16.12     26.12  87.40  7.94      105.5      0
39988        16.18     26.09  89.30  7.98       77.6      0
39989        16.23     26.19  90.80  8.02       64.2      0
39990        16.37     26.21  92.30  8.10       14.3      0
39991        16.34     26.07  92.30  8.06       10.5      0
39992        16.33     25.96  92.10  8.03        9.7      0
39993        16.30     25.79  92.20  7.98       15.3      0
39994        16.28     25.75  92.20  7.97       15.6      0
39995        16.30     25.77  92.20  7.99       17.6      0
39996        16.34     25.84  92.40  8.01       19.2      0
39997        16.39     25.97  92.90  8.05       17.3      0

[39988 rows x 6 columns]

In [11]:
df_work= df_work[['PH','Label']]

In [12]:
df_work.head()

     PH  Label
0  7.88      0
1  7.89      0
2  7.90      0
3  7.91      0
4  7.92      0

In [13]:
df_work.describe()

                 PH    Label
count  39988.000000  39988.0
mean       7.932014      0.0
std        0.203872      0.0
min        7.310000      0.0
25%        7.800000      0.0
50%        7.930000      0.0
75%        8.060000      0.0
max        8.830000      0.0

In [14]:
faults = []
for i in range(400):
    faults.append(random.uniform(0, 1))
    
faults = [i*14 for i in faults]
print(faults)

[10.038219407271264, 7.511727780059833, 10.516662890288876, 5.719671549118521, 11.349156083556654, 4.6119468940697645, 7.033231924043475, 12.089013229929229, 10.294037026301408, 12.795668508179547, 11.220722836470955, 2.8174200971694403, 0.30807701060288406, 12.142444691297495, 10.501833500315701, 8.175671080718512, 11.231602001932783, 1.1686981200896533, 3.3761903758483287, 9.6175012800111, 8.592653244701346, 9.640179188071656, 0.1975419375438796, 2.543724832168065, 11.9119109295347, 4.447863765603201, 11.457844863318606, 12.166650467750783, 5.8955539626277735, 8.99726960009245, 10.12773806664308, 12.708043628596352, 0.7633981652893402, 4.275475422410733, 12.352426491242715, 12.029502749900853, 7.0921385776747465, 13.915756010268604, 6.476660257183111, 5.304857249003141, 9.851926432377338, 9.721982346977438, 3.0620191948883346, 13.638411002944515, 11.097458146129162, 0.2575840583955591, 13.248942311904766, 8.345683409785568, 0.38285255246818983, 7.031357410722381, 2.9416456640188526, 10.45648883904129, 12.902939071764562, 0.8277375908044604, 3.4153330052417203, 11.50835466912487, 8.6515962290642, 3.003737639110278, 2.0228326776179255, 4.096199111211735, 6.939898010087914, 13.138861430092463, 12.624094347025668, 6.268909962340876, 6.625892955445653, 8.430004346772622, 4.10171301233771, 5.3002101696866974, 6.3946409552112575, 12.304425667457894, 4.850322712421196, 5.135077261323545, 7.24363861863952, 9.662074322350698, 2.8111054210061845, 5.214825910608044, 9.958633531272248, 3.2226745595365553, 0.21595604223492249, 11.35726111061959, 5.956235982228343, 5.787904947462368, 9.918701607395786, 7.160901953506331, 10.121746954574864, 13.42495513623577, 9.376485106940565, 8.733386238688468, 3.3888555618592564, 13.364992939576178, 3.559814199491484, 10.826796725705501, 4.131608794392919, 5.294512704978528, 7.308458002008724, 7.6382374204306815, 10.581451214071938, 1.1737741129460981, 3.158295300006536, 5.8994227901291385, 7.125317042169039, 9.627518718859985, 12.945895844355055, 6.412673758761343, 2.363118629690814, 1.5465271231413669, 10.461062732183613, 9.577806270659748, 6.159925066331492, 11.851680667347782, 6.103856199572196, 0.9495279221285928, 8.19992308094961, 6.348081362797686, 0.3788585377406082, 1.5836439649201477, 6.216031264927761, 9.028777800540267, 2.10262011514516, 0.555891193928385, 10.334040835007144, 7.875658116893026, 0.8588582588727285, 5.197477972089468, 11.923511331764457, 13.47189097744002, 7.322449282280621, 9.442991125025742, 8.934786837542807, 1.1898574436945581, 1.3139351589962298, 1.9994655951502138, 10.635805030888193, 12.208908873592707, 0.09679863406252709, 11.8289238928185, 1.9907153281048782, 3.8398856517606963, 0.1974540219473453, 4.5904199312093015, 0.5244138865750785, 1.7524977673482336, 3.9611188090616896, 0.34545551951373676, 1.5679848247265835, 6.997395432883159, 11.886678226351014, 1.3951556050729927, 12.23035294993246, 3.3158157710547917, 7.988629488948555, 12.454470139554392, 12.901866847502612, 5.328141429099753, 5.870842190567243, 10.466397042023472, 7.414150462568951, 11.002637814823826, 2.3498400697068638, 9.950397016149662, 0.07773032108873079, 6.735861244966201, 1.3922585959728537, 5.401196131822692, 2.8033726977950417, 10.276859628108102, 1.2538082436358822, 4.249880030914651, 3.5444020209802316, 5.675156827157505, 3.7560798443624286, 11.835940773275949, 0.5123208311821092, 1.9851928951488365, 10.070926874697697, 0.24954088537260444, 12.434499524510068, 8.698170567618238, 3.9409603404714644, 2.1528844107199197, 13.578436338920401, 3.165271303078261, 1.6182928072061935, 4.834903723954195, 9.530468986567342, 3.987599076056939, 10.649324334584945, 0.7173060335437054, 0.02274446310194289, 10.471580627816888, 9.318974243150642, 3.2502064123775583, 10.754945659346758, 8.904015380586209, 12.292598916119584, 12.379471435254532, 2.8412263198340346, 12.332846578744633, 1.473232245263612, 10.094053960276232, 8.830410842655427, 4.405640830563011, 5.717579670796157, 6.32418789411966, 6.25009796964958, 2.997279995569351, 3.8481780733689046, 13.765876975463343, 8.418490384670898, 5.620217908657998, 2.068984278958038, 12.831843617130444, 0.8074940068335654, 9.44898606906681, 1.168628139481187, 5.912070450623817, 3.9250485203071017, 10.741122035186205, 3.3045704987313087, 0.7276557563706374, 5.871221215902597, 6.556447636061849, 1.4503311755433113, 9.383690588470301, 12.668741168340011, 11.367540678804442, 4.367129369218009, 0.47889672453895904, 10.24599895882671, 11.979480496970833, 9.704366119653269, 8.830431610453257, 8.21218361401675, 0.036241365223619315, 7.796506550726975, 10.423303932137454, 7.157477566153702, 6.427963787931116, 6.4022381405623925, 8.862514247111108, 4.661375888110483, 12.591507859555088, 12.632743084455544, 2.1430239448840203, 8.535187392997559, 0.10517457027219068, 9.602501127205164, 6.086439434028863, 0.706852118681079, 5.092475415794727, 13.111762775239145, 2.3709959384998927, 0.3988304509051839, 13.185262326370406, 13.969244320274393, 2.551239978082968, 11.848890511039176, 12.305598193706176, 9.010155273863203, 6.8525569858348305, 0.6353363527890672, 2.658608562995343, 10.358431612399475, 4.653476743378279, 10.659432635363181, 7.222364971215025, 1.7873748813485637, 13.197231377419426, 9.638229035934781, 5.991043645457303, 3.6738792977588783, 6.237588135694947, 12.214391989997303, 8.601490873905924, 0.7199111332979287, 5.432239585027899, 7.397792847970875, 4.473567154841652, 1.9361321466120385, 3.3275593216894794, 5.134100771490008, 10.554055781483385, 2.314192650716138, 2.9857738211040923, 12.224706975860064, 4.978797604771008, 3.149275932363567, 11.128659535507875, 8.366585975844806, 10.753479554740881, 0.12578069862443497, 10.693066090487495, 5.168024521132795, 0.8365936735767767, 2.002608222935385, 9.424614386832479, 7.883426372667179, 7.5606338374447315, 1.8846069263256022, 5.901128966029628, 4.79837649357588, 12.808190441040669, 3.8118827244506868, 13.685838930903456, 11.050515916904718, 9.648402063881907, 5.582512442908633, 10.738461470867174, 11.632672769562031, 13.925623600880431, 12.356629592513883, 7.498902961706936, 10.457241166782255, 6.481511630210639, 5.5127306682993105, 2.4094417938611725, 12.019662015454003, 8.802388571937936, 11.793706455528776, 10.34522294973342, 6.644078705524199, 1.1226805908945683, 8.875285513611457, 1.3406926732384818, 3.669858191596398, 8.728608488395388, 5.5175341768117825, 1.150477668460406, 2.5469538369448435, 10.154924912198668, 4.136122482505798, 3.915623225020009, 5.581268009351847, 9.469276737813136, 6.106240374272916, 11.651885889627817, 0.9289226722714987, 8.96433891306759, 2.005667085304447, 11.094787329621564, 4.757675064866593, 13.307009578367934, 2.9556340117323936, 0.6067173916018471, 8.539621171971346, 10.324478005307196, 2.2690860343136676, 0.0023672139335875197, 8.961978479466145, 0.6855303785658313, 1.5395757745479421, 7.764052623134364, 3.050743579028026, 2.5014393998165394, 5.957271320760832, 4.650053290086138, 10.948490540320956, 2.1037439381383845, 5.55661675120718, 10.343438361700668, 13.816254351448585, 11.272092973406583, 7.648876125077027, 5.245416145887714, 11.91803742708882, 9.595492675176946, 8.36406465283248, 0.7639901605349937, 13.05414316578415, 0.8421227487302363, 3.2714743424772816, 10.160556222345765, 12.397978645532099, 6.182539736146046, 3.662098620962418, 3.021177441440309, 8.01557290624132, 8.476148529531384, 12.605542252992223, 10.076471092457682, 11.330132011103116, 7.530451771503374, 7.089075598627381, 3.0971248489456613, 12.239158423211453, 1.7601524721727757, 12.545861583341736, 7.533862880518484, 9.780164517537742, 9.128031074298486, 0.9110201150933814, 2.386161789995013, 8.198091064300904, 0.8293066400168281, 9.59388589832896, 13.199562436475963, 1.4281042601905432, 0.042312192468667575, 11.675161034191733, 0.5361766743519167]

In [15]:
for index,i in enumerate(df_work['PH']):
    if(index%100 ==0):
        df_work.at[index,'PH'] = faults[index%400]
        df_work.at[index,'Label']= 1
        
        
diff = pd.DataFrame(df_work.diff())


diff_1 =  pd.DataFrame(diff.loc[:,'PH']<-1)
print(diff_1) 


for index,i in enumerate(diff_1):        
    if(i==True):
        df_work.at[index, 'PH'] = 1
    else:
        df_work.at[index, 'PH'] = 1

          PH
0      False
1       True
2      False
3      False
4      False
5      False
6      False
7      False
8      False
9      False
10     False
11     False
12     False
13     False
14     False
15     False
16     False
17     False
18     False
19     False
20     False
21     False
22     False
23     False
24     False
25     False
26     False
27     False
28     False
29     False
...      ...
39968  False
39969  False
39970  False
39971  False
39972  False
39973  False
39974  False
39975  False
39976  False
39977  False
39978  False
39979  False
39980  False
39981  False
39982  False
39983  False
39984  False
39985  False
39986  False
39987  False
39988  False
39989  False
39990  False
39991  False
39992  False
39993  False
39994  False
39995  False
39996  False
39997  False

[39988 rows x 1 columns]

In [16]:
df_work

         PH  Label
0      1.00      1
1      7.89      0
2      7.90      0
3      7.91      0
4      7.92      0
5      7.95      0
6      7.96      0
7      7.97      0
8      7.98      0
9      7.97      0
10     7.90      0
11     7.91      0
12     7.92      0
13     7.94      0
14     7.96      0
15     8.01      0
16     8.03      0
17     8.09      0
18     8.04      0
19     7.99      0
20     7.97      0
21     7.92      0
22     7.94      0
23     7.96      0
24     7.98      0
25     8.02      0
26     8.00      0
27     7.96      0
28     7.84      0
29     7.85      0
...     ...    ...
39968  8.02      0
39969  8.00      0
39970  8.01      0
39971  8.02      0
39972  8.03      0
39973  8.03      0
39974  8.03      0
39975  8.02      0
39976  8.02      0
39977  8.02      0
39978  8.01      0
39979  8.00      0
39980  8.00      0
39981  7.99      0
39982  7.98      0
39983  7.96      0
39984  7.95      0
39985  7.94      0
39986  7.94      0
39987  7.94      0
39988  7.98      0
39989  8.02      0
39990  8.10      0
39991  8.06      0
39992  8.03      0
39993  7.98      0
39994  7.97      0
39995  7.99      0
39996  8.01      0
39997  8.05      0

[39988 rows x 2 columns]

In [17]:
x = df_work[['PH']]
y = df_work[['Label']]
            
from sklearn.model_selection import train_test_split
            
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3,random_state = 1)

y_train

       Label
37410      0
35863      0
1968       0
15964      0
8348       0
38217      0
21684      0
12373      0
32350      0
30192      0
15215      0
3882       0
31451      0
20644      0
3004       0
10875      0
24995      0
12052      0
31751      0
29905      0
1643       0
27811      0
18607      0
8316       0
12432      0
15914      0
11706      0
12624      0
14660      0
34522      0
...      ...
2561       0
3607       0
37193      0
33809      0
39063      0
33888      0
26113      0
17143      0
19439      0
24545      0
31969      0
27214      0
22936      0
37542      0
19953      0
8450       0
35740      0
21768      0
32035      0
36240      0
31238      0
7756       0
20619      0
32922      0
21450      0
7818       0
32521      0
5195       0
12178      0
33013      0

[27991 rows x 1 columns]

In [18]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

In [19]:
import sklearn

clf = DecisionTreeClassifier()
clf = clf.fit(x_train,y_train)
y_pred = clf.predict(x_test)

print(accuracy_score(y_pred,y_test))
print(list(y_test[0:400]))
print(y_pred[0:400])
#print(X_test[0:400])

print(sklearn.metrics.classification_report(y_test,y_pred))
print(sklearn.metrics.roc_auc_score(y_test,y_pred))

1.0
['Label']
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     11872
           1       1.00      1.00      1.00       125

    accuracy                           1.00     11997
   macro avg       1.00      1.00      1.00     11997
weighted avg       1.00      1.00      1.00     11997

1.0

In [46]:
import sklearn as sk
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
X = np.array(df_work['PH'])
y = np.array(df_work['Label'])
X = X.reshape((-1,1))
LR = LogisticRegression(random_state=1, solver='lbfgs').fit(X,y)



print(LR.intercept_)
print(LR.coef_)

lr = LR.predict(x_test)
print(accuracy_score(y_test,lr))

print(sklearn.metrics.classification_report(y_test,lr ,labels=np.unique(lr)))
print(sklearn.metrics.roc_auc_score(y_test,lr))
metrics.f1_score(y_test, lr, average='weighted', labels=np.unique(lr))

[4.3144739]
[[-1.13443585]]
0.9895807285154622
              precision    recall  f1-score   support

           0       0.99      1.00      0.99     11872

   micro avg       0.99      1.00      0.99     11872
   macro avg       0.99      1.00      0.99     11872
weighted avg       0.99      1.00      0.99     11872

0.5

0.9947630818216096

In [49]:
from sklearn import svm
from sklearn import linear_model 



SVM = svm.LinearSVC(max_iter=5000)
SVM.fit(x_train, y_train)

s = SVM.predict(x_test)


print(accuracy_score(s,y_test))
print(sklearn.metrics.roc_auc_score(y_test,lr))

C:\Users\KOLLICHINMAIVIGNYA\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

0.9895807285154622
0.5

In [51]:
from sklearn.ensemble import RandomForestClassifier

RF = RandomForestClassifier(n_estimators=1, max_depth=8, random_state=1)
RF.fit(x_train, y_train)
rf = RF.predict(x_test)
print(accuracy_score(rf,y_test))
print(sklearn.metrics.classification_report(y_test,rf))
print(sklearn.metrics.roc_auc_score(y_test,rf))

1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     11872
           1       1.00      1.00      1.00       125

    accuracy                           1.00     11997
   macro avg       1.00      1.00      1.00     11997
weighted avg       1.00      1.00      1.00     11997

1.0

C:\Users\KOLLICHINMAIVIGNYA\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.